apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: activemq
spec:
  rules:
  - host: activemq
    http:
      paths:
      - backend:
          service:
            name: activemq-artemis
            port:
              number: 8161
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - activemq
