apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-artemis-usermanagement-service
  name: usermanagement-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployment-artemis-usermanagement-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-artemis-usermanagement-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: artemis-usermanagement-config
            optional: false
        - configMapRef:
            name: jhipster-registry-config
            optional: false
        - secretRef:
            name: artemis-secrets
        image: ghcr.io/ls1intum/artemis-usermanagement-service
        imagePullPolicy: Always
        name: usermanagement-service
        ports:
        - containerPort: 8087
          name: 8087tcp2
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
              - '/bin/sh'
              - '-c'
              - |
                  while true
                  do
                    rt=$(nc -z -w 1 artemis-mysql 3306)
                    if [ $? -eq 0 ]; then
                      echo "DB is UP"
                      break
                    fi
                    echo "DB is not yet reachable;sleep for 10s before retry"
                    sleep 10
                  done
